# 服务端口号
server:
  port: 80

# spring配置
spring:
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
  # 数据库配置
  datasource:
    username: root
    password: root123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8

# mybatis配置
mybatis:
  type-aliases-package: com.oay.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml